### ISSUE TITLE
Refine automated import

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-pad-importer#25]
import-pad.sh is deleting the pelias aliases but not assigning the new alias.  It's also firing before the import is complete.

Troubleshoot and get zero downtime updates working consistently.

**Comment by allthesignals** [comment]
1. I looked into https://www.terraform.io/, which automates infrastructure in code. This might be a helpful tool for instantly standing up different versions of the geocoder without relying on shell scripts. It could also be useful for doing things like setting up a staging environment or development environment instantly. It also provides the added benefit of preserving server infrastructure version control so that we can be sure of what our setup is at any time in one place. 

At this point, it seems difficult to do any development because the local environment differs from our server environment so much. I think we should stand up staging and development droplets and put them on ice when we're not working on them. This issue is otherwise too broad to troubleshoot. 

2. Another tool that might be useful is Ansible: https://www.ansible.com/use-cases/application-deployment.  This seems more or less the same philosophy w/r/t version control but is more specific to the application and how to maintain it. It seems more fully featured than Terraform. 

Either way, I'm not sure if it's worth setting up any of these unless I hear otherwise.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #7](https://github.com/NYCPlanning/labs-geosearch-docker/issues/7) via [**ZenHub**](https://www.zenhub.com/)
